### PR TITLE
idea: enable run via jbang 

### PR DESCRIPTION
**Pull request by maxandersen**
with these changes (main one being to have the repo buildable in jitpack.yml + use jitpack as rep for model.jar) you can do `jbang https://github.com/maxandersen/jfxcentral/blob/jbang`

once merged `jbang https://github.com/dlemmermann/jfxcentral` would work.

could clean that up with a jbang-catalog.json but wanted to try change minimally for now.

 Wether you want it with these changes is up to you - I just saw it as a challenge to see it run :)

### CODE REVIEW

**Comment by aalmiray** [comment]
@maxandersen jfxcentral uses JReleaser thus you may configure the `JBang` packager to publish the script and catalog 😉

@dlemmermann if you'd like to use that option we'll need a personal access token with read/write scope. This would also enable using Homebrew and other packagers in the future.

**Comment by dlemmermann** [comment]
Hi Andres,

token sounds fine to me. You have access to the repo as a contributor, so I guess you can create the token yourself?
The more distribution channels, the better.

Dirk

**Comment by aalmiray** [comment]
Yes, I could create the token but then It'll be attached to my account. It's better if you create the token. Use `GH_PAT` as name when adding the secret to the repo.

**Comment by maxandersen** [comment]
> @maxandersen jfxcentral uses JReleaser thus you may configure the `JBang` packager to publish the script and catalog 😉

how do you customize the script generated by jreleaser ? in this case  need a custom version.

**Comment by dlemmermann** [comment]
Confused regarding the token. We are talking about an access token for the organisation? Got a screenshot?

**Comment by aalmiray** [comment]
@maxandersen just realized jbang packager is not supported for distributions of type NATIVE_PACKAGE as there's no guarantee JARs exist that is, the developer may only have access to installer files. Then again that would be the same case for distros of type JAVA_BINARY and JLINK (however with a small % of occurrence (at least that's my gamble)). 

Also NATIVE_PACKAGE distros may not be Java based though their most common setup may be Java. 

I have to think about the consequences of enabling jbang for NATIVE_PACKAGE but for the time being we should continue using the setup that you have in place.

**Comment by aalmiray** [comment]
@dlemmermann it's up to you if you want to create an access token for an org or not but I think `dlemmermann` where both jfxcentral and the jbang-catalog repos reside is not an org, is it?  https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by dlemmermann** [comment]
True .... will create it but need to know which boxes to check ....

**Pull request merged**
